server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrmanage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 2028
    hikari:
      pool-name: DateHikariCP
      mininum-idle: 5
      idle-timeout: 188888
      maxinum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    timeout: 10000ms
    host: 127.0.0.1
    database: 0
    port: 6379
    password: redispass
    lettuce:
      pool:
        max-active: 1024
        max-wait: 1000ms
        max-idle: 200
        min-idle: 5


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.chen.server.pojo
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: false

logging:
  level:
    com.chen.server.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer
